### ISSUE TITLE
Need a version for Elastic Stack 6.+

### ISSUE THREAD

**Issue by david-reynolds-xedo** [Yelp/elastalert#1466]
looks like the contracts have changed between 5.x and 6.x causing the elastAlert startup to fail 

```
2017-12-19 15:46:43,390 DEBG 'elastalert' stderr output:
WARNING:elasticsearch:GET http://10.10.10.185:9200/elastalert_status/elastalert/_search?size=1000 [status:400 request:0.002s]

2017-12-19 15:46:43,392 DEBG 'elastalert' stderr output:
ERROR:root:Error finding recent pending alerts: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].') {'filter': {'range': {'alert_time': {'to': '2017-12-19T15:46:43.385087Z', 'from': '2017-12-17T15:46:43.384974Z'}}}, 'query': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}, 'sort': {'alert_time': {'order': 'asc'}}}
```

**Comment by vnikitov** [comment]
I think this is related to this issue https://github.com/Yelp/elastalert/issues/1399

**Comment by GoodMirek** [comment]
Seems as a duplicate of now closed #1427.
If you are using old index elastalert_status created before 6.0.0, have a look at #1426.

**Comment by fatalglitch** [comment]
I'm using the bitsensor docker image recommended in your documentation, and on first install I receive this error.

`21:43:21.208Z ERROR elastalert-server:
./node_modules/safe-buffer/index.js                                                                                   │    ProcessController:  WARNING:elasticsearch:GET http://elasticsearch:9200/elastalert_status/elastalert/_search?size=
./src/index.js                                                                                                        │1000 [status:400 request:0.060s]
./src/common/config/index.js                                                                                          │
./src/common/logger/index.js                                                                                          │21:43:21.210Z ERROR elastalert-server:
./src/common/errors/utils/index.js                                                                                    │    ProcessController:  ERROR:root:Error finding recent pending alerts: TransportError(400, u'parsing_exception', u'Un
./src/controllers/rules/index.js                                                                                      │known key for a START_OBJECT in [filter].') {'filter': {'range': {'alert_time': {'to': '2018-02-19T21:43:21.026089Z',
./src/controllers/templates/index.js                                                                                  │'from': '2018-02-17T21:43:21.026051Z'}}}, 'query': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:f
./src/controllers/process/index.js                                                                                    │alse'}}, 'sort': {'alert_time': {'order': 'asc'}}}
./src/controllers/test/index.js                                                                                       │    Traceback (most recent call last):
./src/handlers/status/index.js                                                                                        │      File "/opt/elastalert/elastalert/elastalert.py", line 1396, in find_recent_pending_alerts
./src/handlers/status/control/index.js                                                                                │        size=1000)
./src/handlers/status/errors/index.js                                                                                 │      File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
./src/handlers/rules/index.js                                                                                         │        return func(*args, params=params, **kwargs)
./src/handlers/index.js                                                                                               │      File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 623, in search
./src/handlers/templates/index.js                                                                                     │        doc_type, '_search'), params=params, body=body)
./index.js                                                                                                            │      File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request
/opt/elastalert-server # find . -iname "create*index*"                                                                │        status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
/opt/elastalert-server # find . -iname "*create*index*"                                                               │      File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request
/opt/elastalert-server # find . -iname "elastalert-create*"                                                           │        self._raise_error(response.status_code, raw_data)
/opt/elastalert-server # ll                                                                                           │      File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error
/bin/sh: ll: not found                                                                                                │        raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
/opt/elastalert-server # elastalert-create-index                                                                      │    RequestError: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].')
`

**Comment by fatalglitch** [comment]
Log is below:
`21:51:31.682Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id.                                                                                                                                         [0/1113]
21:51:31.682Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id.
21:51:31.682Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id.
21:51:31.683Z  INFO elastalert-server: Router:  Listening for POST request on /test.
21:51:31.683Z  INFO elastalert-server: Router:  Listening for GET request on /config.
21:51:31.683Z  INFO elastalert-server: Router:  Listening for POST request on /config.
21:51:31.689Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
21:51:31.689Z  INFO elastalert-server: ProcessController:  Creating index
21:51:36.507Z ERROR elastalert-server:
    ProcessController:  Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/opt/elastalert/elastalert/create_index.py", line 154, in <module>
        main()
      File "/opt/elastalert/elastalert/create_index.py", line 138, in main
        es.indices.put_mapping(index=index, doc_type='elastalert', body=es_mapping)
      File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
      File "build/bdist.linux-x86_64/egg/elasticsearch/client/indices.py", line 282, in put_mapping
      File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request
      File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request
      File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error
    elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception', u'No handler for type [string] declared on field [rule_name]')

21:51:36.507Z ERROR elastalert-server: ProcessController:  Index create exited with code 1
21:51:36.507Z  WARN elastalert-server: ProcessController:  ElastAlert will start but might not be able to save its data!
21:51:36.509Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
21:51:36.522Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 47)
21:51:36.524Z  INFO elastalert-server: Server:  Server listening on port 3030
21:51:36.525Z  INFO elastalert-server: Server:  Server started
21:51:37.110Z ERROR elastalert-server:
    ProcessController:  WARNING:elasticsearch:GET http://192.168.12.211:9200/elastalert_status/elastalert/_search?size=1000 [status:400 request:0.002s]

21:51:37.115Z ERROR elastalert-server:
    ProcessController:  ERROR:root:Error finding recent pending alerts: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].') {'filter': {'range': {'alert_time': {'to': '2018-02-19T21:51:37.104725Z', 'from': '2018-02-17T21:51:37.104697Z'}}}, 'query': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}, 'sort': {'alert_time': {'order': 'asc'}}}
    Traceback (most recent call last):
      File "/opt/elastalert/elastalert/elastalert.py", line 1396, in find_recent_pending_alerts
        size=1000)
      File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
        return func(*args, params=params, **kwargs)
      File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 623, in search
        doc_type, '_search'), params=params, body=body)
      File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request
        status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
      File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request
        self._raise_error(response.status_code, raw_data)
      File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error
        raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
    RequestError: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].')
    WARNING:elasticsearch:GET http://192.168.12.211:9200/elastalert_status/elastalert_status/_search?_source_include=endtime%2Crule_name&size=1 [status:400 request:0.002s]
    ERROR:root:Error querying for last run: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].')

21:51:37.393Z ERROR elastalert-server:
    ProcessController:  WARNING:elasticsearch:GET http://192.168.12.211:9200/winlogbeat-*/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:400 request:0.003s]
`

**Comment by david-reynolds-xedo** [comment]
is it too simplistic too say that its an issue with multiple document types on the same elastalertstatus index? if this is the case then can't we (some dev) change the code to use separate indexes rather than doctypes? e.g. elastalert-*

**Comment by andersforsell** [comment]
I am also seeing this problem when using docker images sebp/elk:623 (version 6.2.3) with bitsensor/elastalert:latest

**Comment by fatalglitch** [comment]
Appears this is due to ES 6.0 replacing "string" type with "text", still looking on best way to resolve.

**Comment by ankit22550** [comment]
any update on this issue how to resolve because still i am facing same issue.

**Comment by Qmando** [comment]
To resolve, download the most recent version of elastalert. This has been fixed for a few months now.

**Comment by KelSolaar** [comment]
@Qmando : I had the issue a few weeks ago using latest master from the repo (I don't remember which commit though).

**Comment by Qmando** [comment]
If you can reproduce on master, please open an issue.

**Comment by andersforsell** [comment]
Just checked that this problem still exists when using docker images sebp/elk:624 (version 6.2.4) with bitsensor/elastalert:latest

**Comment by pihlajus** [comment]
If you are building from sources, this issue seems to be fixed now in develop branch.
