### ISSUE TITLE
ImportError: cannot import name 'kibana'

### ISSUE THREAD

**Issue by wajika** [Yelp/elastalert#2915]
![image](https://user-images.githubusercontent.com/17058349/89883712-1b543880-dbfb-11ea-92f1-f554a4fd0b02.png)

I run elastalert.py in the elastalert source directory, but it fails.

**Comment by V1og** [comment]
+1

**Comment by nsano-rururu** [comment]
look
https://my.oschina.net/u/4262664/blog/3326907

**Comment by nsano-rururu** [comment]
Did you contact the plugin developer?

**Comment by V1og** [comment]
I tried the source code installation and encountered the same problem
Solved with pip installation

**Comment by nsano-rururu** [comment]
look
https://stackoverflow.com/questions/59014095/elastalert-deployment-failed

**Comment by nsano-rururu** [comment]
@wajika 

Did you solve? Or unsolved

**Comment by wajika** [comment]
> @wajika
> 
> Did you solve? Or unsolved


I haven't succeeded, I still don't understand why the prompt.

**Comment by nsano-rururu** [comment]
@wajika 

What command are you executing in relation to ElastAlert before the error occurs?

**Comment by nsano-rururu** [comment]
@wajika 

* OS version you are using
* Python version you are using
* Commands executed during ElastAlert installation

**Comment by nsano-rururu** [comment]
@wajika 

[ImportError: cannot import name kibana #2417](https://github.com/Yelp/elastalert/issues/2417)

**Comment by nsano-rururu** [comment]
I'm not sorry about this anymore. goodbye

**Comment by nsano-rururu** [comment]
Please close it already.

**Comment by wajika** [comment]
Sorry, I'm working on other projects now

**Comment by nsano-rururu** [comment]
I'm sorry it didn't help
